### ISSUE TITLE
Vignette / pkgdown site

### ISSUE THREAD

**Issue by graemeleehickey** [thevaachandereng/bayesCT#10]
There is insufficient documentation about the normal and binomial examples. Much more is required here to enable the user to understand what the package can and can't can't do, and what these particular functions do. The help documentation should also be expanded considerably for these functions.

**Comment by thevaachandereng** [comment]
I am waiting to wrap up the function with the summary before completing the documentation.

**Comment by thevaachandereng** [comment]
The documentation is much better now. I made a lot of changes.
