### ISSUE TITLE
Vignette clarification

### ISSUE THREAD

**Issue by graemeleehickey** [thevaachandereng/bayesCT#11]
I like the section in the vignette describing what adaptive trials are used for. However, it needs to be made explicitly clear to the reader what aspect of adaptive trials this package specifically deals with. For example, we don't consider the situation of trials with multiple treatment arms in this package.

**Comment by thevaachandereng** [comment]
I will send you an email about this.

**Comment by thevaachandereng** [comment]
This is also addressed in the new vignette.
