### ISSUE TITLE
Hex sticker

### ISSUE THREAD

**Issue by graemeleehickey** [thevaachandereng/bayesCT#19]
We discussed possibly having a hex sticker for bayesCT. Seems quite standard these days, and can be made using the following R package:

https://github.com/GuangchuangYu/hexSticker

Do you have any ideas for what could be used here?

**Comment by thevaachandereng** [comment]
I added the hexSticker to `https://github.com/thevaachandereng/bayesCT/blob/master/man/figures/logo.png`
