### ISSUE TITLE
British vs. American English

### ISSUE THREAD

**Issue by graemeleehickey** [thevaachandereng/bayesCT#6]
One place I see frustration emerging is in the different spellings of randomisation and enrolment.

1. enrolment (UK) versus enrollment (US)
2. randomisation (UK) versus randomization (US)

Is there a simple way to mask this internally? Or do we just have to be careful in spelling?

**Comment by thevaachandereng** [comment]
@graemeleehickey I am not sure if there is a way to mask it. I will look into this option right away.
