### ISSUE TITLE
Help documentation PDF

### ISSUE THREAD

**Issue by graemeleehickey** [thevaachandereng/bayesCT#8]
When using roxygen2 for documentation, I have previously found that I needed to run Code -> Reflow comment on the text to ensure that the lines do not go off the page when LaTeX'ed.

I have done that with a couple of files, but that is only because it helps me read rmarkdown in RStudio without scrolling.

Is this worth applying to the markdown throughout?

**Comment by thevaachandereng** [comment]
I am not so sure about this. I will look into this. I am not so familiar with the roxygen2 documentation. I have only used it to generated rd files.

**Comment by graemeleehickey** [comment]
Looks like this has been resolved.
